### ISSUE TITLE
MarketAssessment.Save() fails on Time granularities

### ISSUE THREAD

**Issue by AndreaCuneo** [ARKlab/Artesian.SDK#11]
When calling Save() on a MarketAssessment with a Time OriginalGranularity, the library sends the wrong UpsertData.

VersionedTimeSerie and ActualTimeSerie correctly set the UpsertData.Timezone to flag the Timezone of the data payload. MarketAssessment fails to do so.

**Comment by NiallArkEnergy** [comment]
Fixed with https://github.com/ARKlab/Artesian.SDK/commit/f202bae061b641ff2c0d35077955d061a3b72f50
